### ISSUE TITLE
Text with `new line` should be displayed on one line

### ISSUE THREAD

**Issue by gzoritchak** [data2viz/data2viz#118]
The current version of the library does not support multiline. 

The rendering has to be the same on each platform. As a result, texts should be "cleaned" with a warning to remove the new lines (and not rendering multi lines on platforms that support it).

Multiline rendering will be adressed by another issue.

**Comment by xal** [comment]
I propose to replace `\n` with space ` ` instead of removing. Usually, people didn't add ending space in line before '\n'. I can also implement double space trimming in this case, but I think it is not necessary
