### ISSUE TITLE
Forces tutorial is outdated

### ISSUE THREAD

**Issue by osipxd** [data2viz/data2viz#120]
Looks like API was changed but tutorial page wasn't updated: https://play.data2viz.io/tutorials/forces/

**Comment by pmariac** [comment]
Hi, can you please detail a bit more cause everything works fine for me.
Which version of data2viz are you using ? Which platform do you target ?

**Comment by osipxd** [comment]
Ah, ok. Looks like my version is outdated. I used 0.7.1 before. Switched 0.7.2-RC1 and everything works now.
There are a lot of breaking API changes why just patch version incremented?

**Comment by gzoritchak** [comment]
@osipxd Thank you for your feedback. 

Currently, we are adding numbers to versions when we add features. The next major release (V0.8) will include event management. 

We still working on the API to get it better and you could see some other modification before the V1.0. We are going to pay more attention to the changelogs. 

I created a post on our forum to give more information about the roadmap: https://forum.data2viz.io/t/data2viz-roadmap/63
