### ISSUE TITLE
Creating a custom rectnode

### ISSUE THREAD

**Issue by abangkis** [data2viz/data2viz#153]
Hi is there a guide to create a custom node. I notice that rectnode is a final class. So we can only extends from the node class? How do we style the node to be similar like the image?

Thanks

![erd](https://user-images.githubusercontent.com/211071/65648506-b288bf80-e02c-11e9-8eef-229004ef091a.png)

**Comment by gzoritchak** [comment]
In data2viz, you can't extend the graphic hierarchy. You use it by composition. If you want to create a higher-level component, you have to create a function that combines lower-level nodes (rectangles, circle, path, text).  The result of this function is a tree that represents what you want. See this example: https://beta.data2viz.io/gaetan/sketches/XYVRRY/edit/

![image](https://user-images.githubusercontent.com/1110254/65693665-f43d5880-e074-11e9-9dbb-3ede11b4c6ec.png)

**Comment by abangkis** [comment]
Okay. Thanks a lot for the explanation & the examples.
