### ISSUE TITLE
Network visualizer

### ISSUE THREAD

**Issue by abangkis** [data2viz/data2viz#154]
I want to create a network visualizer, starting with ER Diagram and probably expanded to other network such as microservice deployment. The current ERD tools on the market usually static and used for designing the database table (outside of static view). What I'm planning is something more like a d3js network visualization. Where a table that has large relation is shown large and the smaller table would cluster on it. Other than that it would be possible to visualize when a table is modified (add/drop column) and other stuff like that.
After assessing, I don't think I can do it easily with data2viz. But instead I should fork data2viz, extract the network, force class, and canvas drawing classes and try to customize it to the use case. 
So i was wondering how much of an effort would it be (some rough estimation)? From your point of view, could it be done by a single Dev as weekend project?  
Thank you very much for your feedback.

**Comment by gzoritchak** [comment]
Sorry for this late response, I missed your question.

I'm not sure that data2viz is the right solution for your needs. Data2viz is a solution dedicated to data visualization. In your case, you would probably use 10% of it without many gains. 

You should probably draw directly on the Canvas of your targeted platform and possibly copy the network algorithms you need.

**Comment by abangkis** [comment]
Okay. Thanks a lot for your explanation. Appreciate it 👍
