### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by yay** [data2viz/data2viz#18]
Why of all the class and singleton names these particular ones should start with a lowercase letter?

`scales.continuous.linear { }`

instead of

`Scales.Continuous.linear { }`

This strikes me as a very odd and arbitrary decision.

**Comment by gzoritchak** [comment]
Thanks for your feedback,

We didn't make any definitive choices yet. We still have work to do on API coherence and this kind of conventions. 

Normally, we shouldn't use this kind of construction but it can be interesting inside a DSL. It's an easy way of finding the different options when you know the basic concepts: colors, scales, ... At one moment we'll have to decide if we stick to kotlin conventions or if we consider these parts of code as an internal DSL. Taking some distance with the convention can make sense if it gives more coherence.

**Comment by yay** [comment]
Thank you for the explaining your reasoning.

It should be possible to import the `linear` part for DSL to look nice and clean.

As for nesting objects that way for discoverability, I think, it makes perfect sense.

**Comment by yay** [comment]
Good to know!
