### ISSUE TITLE
Examples from README not working

### ISSUE THREAD

**Issue by jonek** [data2viz/data2viz#2]
The README of your repository contains two links to examples:
http://data2viz.io/dist/chart.html
http://data2viz.io/dist/svgperfs.html
both are not working for me neither in Firefox nor in Chrome.

**Comment by holgerbrandl** [comment]
And they also fail to render on Android

**Comment by gzoritchak** [comment]
I will do some cleaning really soon. Stay tuned.

**Comment by gzoritchak** [comment]
I moved the first example (chart) inside an example project (https://github.com/data2viz/data2viz-examples) and corrected the README file accordingly. 

We'll add new examples in that project.
