### ISSUE TITLE
Target is updated two times

### ISSUE THREAD

**Issue by AlbanSeurat** [data2viz/data2viz#20]
The original code is changing the speed on the source as well

https://github.com/d3/d3-force/blob/84d033544347dc2aa3c9e9152c0e91c2eb5e0303/src/link.js#L41-L44

https://github.com/data2viz/data2viz/blob/3432f93ecad83ef3f89b915b535a2da887b8db73/force/d2v-force-common/src/main/kotlin/io/data2viz/force/ForceLink.kt#L111

**Comment by pmariac** [comment]
Nice pick on this one, the second update should indeed be for source...
