### ISSUE TITLE
[Feature Request] Allow drawing images/icons

### ISSUE THREAD

**Issue by Namnodorel** [data2viz/data2viz#219]
It would be handy if there was a way to draw a given PNG or SVG within a visualization, to allow labelling in a more visual way.

**Comment by gzoritchak** [comment]
It's now possible to add an image node:

```
viz.image {
	x = 200.0
	y = 200.0
	size = Size(50.0,50.0)
	image = img.toLocalImage()
}
```
The image is a link to an Image in the platform. 
Depending on the platform there are some extension function to retrieve the image:

JS: `HTMLImageElement.toLocalImage()`
Android: `Bitmap.toLocalImage()`
JFx: `Image.toLocalImage()`
