### ISSUE TITLE
[Feature request] Export as SVG

### ISSUE THREAD

**Issue by Jolanrensen** [data2viz/data2viz#239]
To use renders and plots in papers it would be very useful to be able to export them to a vector format like SVG.
As indicated by the developers, there already exists a small conversion to SVG for geoms: https://github.com/data2viz/data2viz/blob/33d381fb6349877c9cafe084cb69c3a6f8a86349/core/src/commonMain/kotlin/io/data2viz/geom/PathGeom.kt#L138 but this isn't the case yet for everything that can be rendered.
I don't how much work it would be or how easy it would be per-platform. 

If I'm correct, we would need new renderers like for Jfx (https://github.com/data2viz/data2viz/tree/master/viz/src/jfxMain/kotlin/io/data2viz/viz) but then to create an SVG string right?

**Comment by Jolanrensen** [comment]
I started working on it here https://github.com/Jolanrensen/data2viz/tree/svg-export
It's a first draft, but some basic things seem to work already! 
Gradients don't work yet, images probably never will work and I've still got some render issues with entire plots (I probably missed some attributes), but, it's a start :)
Will continue with it later

**Comment by gzoritchak** [comment]
I merged the current work, and I'm going to release it in version 0.8.17. 

We'll have to wait for the HeadlessVizContainer to implement the export for VizContainer (to do some tests).

**Comment by LouisCAD** [comment]
I think we can close this issue as the latest released fixed most text rendering problems, and added support to generate SVG out of a `VizContainer`?
