### ISSUE TITLE
chart in loop ?

### ISSUE THREAD

**Issue by Reqeique** [data2viz/data2viz#250]
was searching for a while but never found any helpful topic on how to express continuous and streamed data in moving graph to generalize assume 
```kt
var x = 0
while(true){
   x++
   // displaying x in continuous manner
}
```
tried approach that behaves almost exactly like the code below
```kt
val p = Pane()
                            var x = 1.0
                            val viz = p.newVizContainer().apply {
                                size = Size(width, height)
                            }
                            while(true) {
                                x++
                                values[1] = x

                                print(values)



                                //  while(true) {
                                viz.chart(values) {
                                    val values = quantitative({ domain })

                                    plot(values, values)
                                }
                                //  }

                                val scene = Scene(p, width, height)
                                jfxpanel.scene = scene
              }
```
but never succeed

**Comment by pmariac** [comment]
It is actually impossible to update data in the current version of charts. 
It will be available in a near future with the introduction of the ChartModel.

What you can do right now, if your chart is very light and draw fast, is to completely clean and redraw everything.

By the way, it is easier for us to track issues on the data2viz forum when it concerns the Charts-kt project: https://forum.data2viz.io/ just create a thread in the charts-kt section.

**Comment by Reqeique** [comment]
Thanks for the response @pmariac ,
was able to resolve the issue by executing it asynchronously to be more specific using coroutines, also in the case of mine it was simple chart which represent 1 dimensional data with single line graph additional as was mentioned by you redrawing in the canvas seems to be super smooth in both higher and lower stream rate with reasonably lower resources usage(mem) 
would also like to give a try to the ChartModel in the near future
here's the code in case
```kt
val p = Pane()
var x = 1.0
val viz = p.newVizContainer().apply {
         size = Size(width, height)
 }
scope { this: CoroutineScope

          while(true) {
                x++
                values[1] = x
                viz.chart(values) {
                val values = quantitative({ domain })
                line(values, values)
         }
}
val scene = Scene(p, width, height)
jfxpanel.scene = scene
```
