### ISSUE TITLE
Implement all rendering tests of Path.arc

### ISSUE THREAD

**Issue by gzoritchak** [data2viz/data2viz#28]
Due to the differences in arc API on each platform, all cases should be tested on all platforms with a comparison of the rendered images.

start; end; counterclocwise;
0; 0.25PI; false
0; 0.25PI; true
0; 2.0PI; true
0; 2.0PI; false
.25PI; 2.25PI; true
.25PI; 2.25PI; false
...

**Comment by pmariac** [comment]
JS : startAngle + endAngle if (end - start) > 2PI should not result%2PI else arc angle is "0"

**Comment by pmariac** [comment]
- add test in RenderingTestSupport
- launch gradle "diffs" task
- if result is ok, copy the result "image.png" in common/resources for IC tests

**Comment by pmariac** [comment]
there is still a minor bug on android when drawing a path over a filled arc with counterclockwise order and angle > 2 PI.... I create a specific bug for this one, but this issue can be merged as 99% of the job seems to be done.
