### ISSUE TITLE
Make travis works with android, JavaFx, and Js

### ISSUE THREAD

**Issue by gzoritchak** [data2viz/data2viz#29]
Travis CI fails on android configuration:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> The SDK directory '/Users/gaetan/Library/Android/sdk' does not exist.
```

See https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
and https://docs.travis-ci.com/user/languages/android/

**Comment by erikthered** [comment]
I can give this one a try

**Comment by gzoritchak** [comment]
You're welcome. 

By default, android modules are not activated (see https://github.com/data2viz/data2viz/blob/master/gradle.properties#L8). Changing that property to true makes all android gradle projects activated. They are mainly the android version of some module but there is also two applications. 

examples/app is the code of https://play.google.com/store/apps/details?id=io.data2viz.data2canvas

and viz/rendering-app is used to test the rendering on android (see https://youtu.be/jnUtiyrpBCY?t=1637)

**Comment by martinbonnin** [comment]
I tried something there: https://github.com/martinbonnin/data2viz/commit/4e233b288985dd0ff75109df804965386c9ea7be.

For some reason travis-ci.org does not see my repo yet so cannot test yet. I'll update this thread if it ever works

**Comment by erikthered** [comment]
@gzoritchak I'm trying to do this via Travis' build matrix, does the project have an easy way to run a task against subprojects with a specified platform only (_-android_ in this case)?
