### ISSUE TITLE
Prerelase artifacts?

### ISSUE THREAD

**Issue by holgerbrandl** [data2viz/data2viz#3]
I know it's prerelaese at the moment, but is there any chance you provide public artifacts for prerelaese builds?

The project looks really promising, pls keep going😀

**Comment by gzoritchak** [comment]
Thanks a lot.

We are moving a lot of things now. I'm going to try to make it more usable. 

I push artefacts on bintray:

https://bintray.com/data2viz/data2viz/data2viz/0.2.3

We should publish soon a new release with shape finished. 

Work in progress (left is canvas, center svg, right d3js) ;-):

![image](https://user-images.githubusercontent.com/1110254/32689780-d4ee3bfc-c6ea-11e7-8dd5-f01f5ddff684.png)

**Comment by gzoritchak** [comment]
I updated the README.md and created the project to show how to use the library.
