### ISSUE TITLE
Rename color extension property to col

### ISSUE THREAD

**Issue by gzoritchak** [data2viz/data2viz#72]
In order to keep lines short and to be consistent with other extension property, we should try to have a maximum of 3 characters for each extension property.

- `.col` : create Color from Int or String
- `.deg` : create an Angle from a number representing degrees
- `.rad` : create an Angle from a number representing radians
- `.pct` : create a Percent from a number

**Comment by pmariac** [comment]
Had the same idea, great. I'm on it.
